INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add manufacturer', 7, 'add_manufacturer');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change manufacturer', 7, 'change_manufacturer');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete manufacturer', 7, 'delete_manufacturer');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view manufacturer', 7, 'view_manufacturer');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add product', 8, 'add_product');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change product', 8, 'change_product');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete product', 8, 'delete_product');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view product', 8, 'view_product');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add product images', 9, 'add_productimages');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change product images', 9, 'change_productimages');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete product images', 9, 'delete_productimages');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view product images', 9, 'view_productimages');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add genre', 10, 'add_genre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change genre', 10, 'change_genre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete genre', 10, 'delete_genre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view genre', 10, 'view_genre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add game', 11, 'add_game');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change game', 11, 'change_game');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete game', 11, 'delete_game');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view game', 11, 'view_game');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add profile', 12, 'add_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change profile', 12, 'change_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete profile', 12, 'delete_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view profile', 12, 'view_profile');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add search history', 13, 'add_searchhistory');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change search history', 13, 'change_searchhistory');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete search history', 13, 'delete_searchhistory');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view search history', 13, 'view_searchhistory');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add review', 14, 'add_review');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change review', 14, 'change_review');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete review', 14, 'delete_review');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view review', 14, 'view_review');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can add order history', 15, 'add_orderhistory');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can change order history', 15, 'change_orderhistory');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can delete order history', 15, 'delete_orderhistory');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can view order history', 15, 'view_orderhistory');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can add game review', 16, 'add_gamereview');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can change game review', 16, 'change_gamereview');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can delete game review', 16, 'delete_gamereview');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can view game review', 16, 'view_gamereview');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can add payment information', 17, 'add_paymentinformation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can change payment information', 17, 'change_paymentinformation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can delete payment information', 17, 'delete_paymentinformation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can view payment information', 17, 'view_paymentinformation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can add shipping information', 18, 'add_shippinginformation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can change shipping information', 18, 'change_shippinginformation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can delete shipping information', 18, 'delete_shippinginformation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can view shipping information', 18, 'view_shippinginformation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (73, 'Can add order', 19, 'add_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (74, 'Can change order', 19, 'change_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (75, 'Can delete order', 19, 'delete_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (76, 'Can view order', 19, 'view_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (77, 'Can add console', 20, 'add_console');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (78, 'Can change console', 20, 'change_console');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (79, 'Can delete console', 20, 'delete_console');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (80, 'Can view console', 20, 'view_console');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (81, 'Can add extra images', 21, 'add_extraimages');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (82, 'Can change extra images', 21, 'change_extraimages');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (83, 'Can delete extra images', 21, 'delete_extraimages');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (84, 'Can view extra images', 21, 'view_extraimages');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (85, 'Can add cart', 22, 'add_cart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (86, 'Can change cart', 22, 'change_cart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (87, 'Can delete cart', 22, 'delete_cart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (88, 'Can view cart', 22, 'view_cart');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (89, 'Can add cart items', 23, 'add_cartitems');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (90, 'Can change cart items', 23, 'change_cartitems');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (91, 'Can delete cart items', 23, 'delete_cartitems');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (92, 'Can view cart items', 23, 'view_cartitems');