# Generated by Django 3.0.5 on 2020-05-13 11:59

import creditcards.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out', models.BooleanField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('card_number', creditcards.models.CardNumberField(max_length=25)),
                ('expiration_date', creditcards.models.CardExpiryField()),
                ('cvv', creditcards.models.SecurityCodeField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('cartID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Cart')),
                ('payment_information_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.PaymentInformation')),
                ('shipping_information_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.ShippingInformation')),
            ],
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Order'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_information_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.PaymentInformation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shipping_information_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ShippingInformation'),
        ),
    ]
