# Generated by Django 3.0.5 on 2020-05-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='profileID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile'),
        ),
    ]
