# Generated by Django 3.0.5 on 2020-05-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200513_1159'),
        ('main', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_information_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_information_id',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='cartID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Cart'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Product'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PaymentInformation',
        ),
        migrations.DeleteModel(
            name='ShippingInformation',
        ),
    ]
