scp *.cpp lokih@skel.ru.is:~/cpp/PA5/
scp Makefile lokih@skel.ru.is:~/cpp/PA5/
scp Classes/*.cpp lokih@skel.ru.is:~/cpp/PA5/Classes
scp Classes/*.h lokih@skel.ru.is:~/cpp/PA5/Classes
scp Helpers/*.cpp lokih@skel.ru.is:~/cpp/PA5/Helpers
scp Helpers/*.h lokih@skel.ru.is:~/cpp/PA5/Helpers
scp Helpers/Structs/*.cpp lokih@skel.ru.is:~/cpp/PA5/Helpers/Structs
scp Helpers/Structs/*.h lokih@skel.ru.is:~/cpp/PA5/Helpers/Structs
scp Helpers/SubMenus/*.cpp lokih@skel.ru.is:~/cpp/PA5/Helpers/SubMenus
scp Helpers/SubMenus/*.h lokih@skel.ru.is:~/cpp/PA5/Helpers/SubMenus
scp Models/*.cpp lokih@skel.ru.is:~/cpp/PA5/Models
scp Models/*.h lokih@skel.ru.is:~/cpp/PA5/Models
scp Templates/ActionTemplates/*.cpp lokih@skel.ru.is:~/cpp/PA5/Templates/ActionTemplates
scp Templates/ActionTemplates/*.h lokih@skel.ru.is:~/cpp/PA5/Templates/ActionTemplates
scp Templates/IndividualTemplates/*.cpp lokih@skel.ru.is:~/cpp/PA5/Templates/IndividualTemplates/
scp Templates/IndividualTemplates/*.h lokih@skel.ru.is:~/cpp/PA5/Templates/IndividualTemplates/
scp Resources/*.txt lokih@skel.ru.is:~/cpp/PA5/Resources
scp Saves/*.txt lokih@skel.ru.is:~/cpp/PA5/Saves
scp Saves/backups/*.txt lokih@skel.ru.is:~/cpp/PA5/Saves/backups