from my_array_deque import ArrayDeque
from my_linked_list import LinkedList
from my_stack import Stack
from my_queue import Queue

print("\nTESTING ARRAY_DEQUE\n")

deque = ArrayDeque()
deque.pushBack(3)
deque.pushBack(1)
deque.pushBack(6)
deque.pushBack(9)
print("container of size: " + str(deque.getSize()) + ":")
print(deque)
print(deque.popBack())
print(deque.popBack())
print("container of size: " + str(deque.getSize()) + ":")
print(deque)
deque.pushFront(11)
deque.pushFront(16)
deque.pushFront(13)
print("container of size: " + str(deque.getSize()) + ":")
print(deque)
print(deque.popFront())
print(deque.popFront())
print(deque.popFront())
print("container of size: " + str(deque.getSize()) + ":")
print(deque)
print(deque.popFront())
print(deque.popBack())
print(deque.popFront())
print(deque.popBack())
print("container of size: " + str(deque.getSize()) + ":")
print(deque)


print("\nTESTING LINKED_LIST\n")

lis = LinkedList()
lis.pushBack(3)
lis.pushBack(1)
lis.pushBack(6)
lis.pushBack(9)
print("container of size: " + str(lis.getSize()) + ":")
print(lis)
print(lis.popFront())
print(lis.popFront())
print("container of size: " + str(lis.getSize()) + ":")
print(lis)
lis.pushFront(11)
lis.pushFront(16)
lis.pushFront(13)
print("container of size: " + str(lis.getSize()) + ":")
print(lis)
print(lis.popFront())
print(lis.popFront())
print(lis.popFront())
print(lis.popFront())
print("container of size: " + str(lis.getSize()) + ":")
print(lis)
print(lis.popFront())
print(lis.popFront())
print("container of size: " + str(lis.getSize()) + ":")
print(lis)


print("\nTESTING QUEUE WITH ARRAYS\n")

queue = Queue("array")
queue.add(2)
queue.add(4)
queue.add(7)
print("the data structure is of size: " + str(queue.getSize()))
print(queue.remove())
print(queue.remove())
print(queue.remove())
print(queue.remove())
print("the data structure is of size: " + str(queue.getSize()))

print("\nTESTING STACK WITH ARRAYS\n")

stack = Stack("array")
stack.push(2)
stack.push(4)
stack.push(7)
print("the data structure is of size: " + str(stack.getSize()))
print(stack.pop())
print(stack.pop())
print(stack.pop())
print(stack.pop())
print("the data structure is of size: " + str(stack.getSize()))

print("\nTESTING QUEUE WITH LINKED_LIST\n")

queue = Queue("linked")
queue.add(2)
queue.add(4)
queue.add(7)
print("the data structure is of size: " + str(queue.getSize()))
print(queue.remove())
print(queue.remove())
print(queue.remove())
print(queue.remove())
print("the data structure is of size: " + str(queue.getSize()))

print("\nTESTING STACK WITH LINKED_LIST\n")

stack = Stack("linked")
stack.push(2)
stack.push(4)
stack.push(7)
print("the data structure is of size: " + str(stack.getSize()))
print(stack.pop())
print(stack.pop())
print(stack.pop())
print(stack.pop())
print("the data structure is of size: " + str(stack.getSize()))
