scp *.cpp lokih@skel.ru.is:~/cpp/PA4/
scp Classes/*.cpp lokih@skel.ru.is:~/cpp/PA4/Classes
scp Classes/*.h lokih@skel.ru.is:~/cpp/PA4/Classes
scp Helpers/*.cpp lokih@skel.ru.is:~/cpp/PA4/Helpers
scp Helpers/*.h lokih@skel.ru.is:~/cpp/PA4/Helpers
scp Models/*.cpp lokih@skel.ru.is:~/cpp/PA4/Models
scp Models/*.h lokih@skel.ru.is:~/cpp/PA4/Models
scp Templates/*.cpp lokih@skel.ru.is:~/cpp/PA4/Templates
scp Templates/*.h lokih@skel.ru.is:~/cpp/PA4/Templates
scp Resources/*.txt lokih@skel.ru.is:~/cpp/PA4/Resources
scp Saves/*.txt lokih@skel.ru.is:~/cpp/PA4/Saves
scp Saves/backups/*.txt lokih@skel.ru.is:~/cpp/PA4/Saves/backups